site_name: 学习笔记
site_url: https://junzzzz.github.io/study-docs/
site_author: Junzzzz
site_description: "学习笔记"
edit_uri: https://github.com/Junzzzz/study-docs/blob/main/docs/

# Repository
# repo_name: Junzzzz/SkillAPI
# repo_url: https://github.com/Junzzzz/SkillAPI

# Copyright
copyright: Copyright &copy; 2022 Junzzzz

# Configuration
theme:
  name: material
  language: zh
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换夜晚模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换白天模式
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      # auto_title: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Junzzzz
      repo: SkillAPI
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - '首页': index.md
  - '游戏开发':
    - 'Unity': 
      - 'AssetBundle': game/unity/assetbundle.md
      - '协程': game/unity/coroutine.md
    - '物理': 
      - '碰撞检测': game/physics/collision-detection.md
      - '旋转': game/physics/rotation.md
  - 'C#':
    - 'collection': c-sharp/collection.md
    - 'yield': c-sharp/yield.md
  - 'GAMES课程':
    - 'GAMES101':
        - '第4讲课后题': games-course/games101/lecture-4-question.md
        - '课程 1-5 总结': games-course/games101/summary-1-5.md
  # - '网络':

